<?php

/**
 * Test class for TagService.
 * Generated by PHPUnit on 2013-08-31 at 01:34:48.
 */
class LangTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TagService
     */
    protected $app;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     */
    public function testExplode() {
        $str = '1，2,3 , 4 ';
        $str = str_replace('，', ',', $str);
        $ar =  explode(',', $str);
        foreach ($ar as &$item) {
            $item = trim($item);
        }
        print_r($ar);
    }

}

